export type EmojiEntry = Readonly<{
  emoji: string
  keywords: ReadonlyArray<string>
}>

export const emojiGroupIds = [
  'smileys',
  'people',
  'nature',
  'food',
  'activity',
  'travel',
  'objects',
  'symbols',
] as const

export type EmojiGroupId = (typeof emojiGroupIds)[number]

export type EmojiGroup = Readonly<{
  id: EmojiGroupId
  emojis: ReadonlyArray<EmojiEntry>
}>

export const emojiGroups: ReadonlyArray<EmojiGroup> = [
  {
    id: 'smileys',
    emojis: [
      { emoji: '😀', keywords: ['sorriso', 'feliz', 'grin', 'smile', 'happy'] },
      { emoji: '😃', keywords: ['sorriso', 'alegre', 'smile', 'happy'] },
      { emoji: '😄', keywords: ['rindo', 'feliz', 'laugh', 'happy'] },
      { emoji: '😁', keywords: ['sorriso', 'dentes', 'grin', 'beam'] },
      { emoji: '😆', keywords: ['gargalhada', 'laughing', 'haha'] },
      { emoji: '😅', keywords: ['riso', 'nervoso', 'sweat', 'laugh', 'alivio'] },
      { emoji: '🤣', keywords: ['rolando', 'de', 'rir', 'rofl', 'lol'] },
      { emoji: '😂', keywords: ['chorando', 'de', 'rir', 'joy', 'lol', 'tears'] },
      { emoji: '🙂', keywords: ['sorriso', 'leve', 'slight', 'smile'] },
      { emoji: '🙃', keywords: ['de', 'cabeca', 'para', 'baixo', 'upside', 'down'] },
      { emoji: '😉', keywords: ['piscada', 'wink'] },
      { emoji: '😊', keywords: ['feliz', 'corado', 'blush', 'smile'] },
      { emoji: '😇', keywords: ['anjo', 'inocente', 'angel', 'halo'] },
      { emoji: '🥰', keywords: ['apaixonado', 'coracoes', 'love', 'hearts'] },
      { emoji: '😍', keywords: ['olhos', 'de', 'coracao', 'heart', 'eyes', 'love'] },
      { emoji: '🤩', keywords: ['estrelas', 'nos', 'olhos', 'star', 'struck', 'uau'] },
      { emoji: '😘', keywords: ['beijo', 'kiss'] },
      { emoji: '🥲', keywords: ['sorriso', 'com', 'lagrima', 'tear', 'smile'] },
      { emoji: '😋', keywords: ['delicioso', 'yum', 'saboroso'] },
      { emoji: '😛', keywords: ['lingua', 'tongue'] },
      { emoji: '😜', keywords: ['lingua', 'piscada', 'zany', 'wink', 'tongue'] },
      { emoji: '🤪', keywords: ['doido', 'zany', 'maluco'] },
      { emoji: '🤑', keywords: ['dinheiro', 'money', 'mouth', 'rico'] },
      { emoji: '🤗', keywords: ['abraco', 'hug'] },
      { emoji: '🤭', keywords: ['risinho', 'mao', 'na', 'boca', 'giggle', 'oops'] },
      { emoji: '🤫', keywords: ['silencio', 'shush', 'segredo', 'quiet'] },
      { emoji: '🤔', keywords: ['pensando', 'thinking', 'duvida'] },
      { emoji: '🤐', keywords: ['boca', 'fechada', 'zipper', 'segredo'] },
      { emoji: '🤨', keywords: ['sobrancelha', 'erguida', 'raised', 'eyebrow', 'duvida'] },
      { emoji: '😐', keywords: ['neutro', 'neutral'] },
      { emoji: '😑', keywords: ['sem', 'expressao', 'expressionless'] },
      { emoji: '😶', keywords: ['sem', 'boca', 'no', 'mouth', 'mudo'] },
      { emoji: '😏', keywords: ['malicioso', 'smirk'] },
      { emoji: '😒', keywords: ['emburrado', 'unamused', 'chateado'] },
      { emoji: '🙄', keywords: ['revirando', 'os', 'olhos', 'eye', 'roll'] },
      { emoji: '😬', keywords: ['careta', 'grimace', 'constrangido'] },
      { emoji: '🤥', keywords: ['mentira', 'lying', 'pinoquio'] },
      { emoji: '😌', keywords: ['aliviado', 'relieved', 'calmo'] },
      { emoji: '😔', keywords: ['pensativo', 'triste', 'pensive'] },
      { emoji: '😪', keywords: ['sono', 'sleepy'] },
      { emoji: '🤤', keywords: ['babando', 'drooling'] },
      { emoji: '😴', keywords: ['dormindo', 'sleeping', 'zzz'] },
      { emoji: '😷', keywords: ['mascara', 'mask', 'doente'] },
      { emoji: '🤒', keywords: ['febre', 'termometro', 'thermometer', 'doente', 'sick'] },
      { emoji: '🤕', keywords: ['machucado', 'bandage', 'ferido'] },
      { emoji: '🤢', keywords: ['enjoado', 'nauseated', 'nojo'] },
      { emoji: '🤮', keywords: ['vomitando', 'vomiting'] },
      { emoji: '🤧', keywords: ['espirro', 'sneezing', 'resfriado'] },
      { emoji: '🥵', keywords: ['calor', 'hot', 'suando'] },
      { emoji: '🥶', keywords: ['frio', 'cold', 'congelando'] },
      { emoji: '🥴', keywords: ['tonto', 'woozy'] },
      { emoji: '😵', keywords: ['atordoado', 'dizzy'] },
      { emoji: '🤯', keywords: ['explodindo', 'mind', 'blown'] },
      { emoji: '🤠', keywords: ['caubói', 'cowboy'] },
      { emoji: '🥳', keywords: ['festa', 'party', 'comemoracao'] },
      { emoji: '😎', keywords: ['oculos', 'escuros', 'sunglasses', 'cool'] },
      { emoji: '🤓', keywords: ['nerd', 'geek', 'oculos'] },
      { emoji: '🧐', keywords: ['monoculo', 'monocle', 'investigando'] },
      { emoji: '😕', keywords: ['confuso', 'confused'] },
      { emoji: '😟', keywords: ['preocupado', 'worried'] },
      { emoji: '🙁', keywords: ['triste', 'frowning'] },
      { emoji: '😮', keywords: ['surpreso', 'open', 'mouth', 'uau'] },
      { emoji: '😲', keywords: ['chocado', 'astonished'] },
      { emoji: '😳', keywords: ['corado', 'flushed', 'vergonha'] },
      { emoji: '🥺', keywords: ['suplicante', 'pleading', 'please'] },
      { emoji: '😨', keywords: ['assustado', 'fearful', 'medo'] },
      { emoji: '😰', keywords: ['ansioso', 'anxious', 'suor'] },
      { emoji: '😥', keywords: ['decepcionado', 'sad'] },
      { emoji: '😢', keywords: ['chorando', 'crying', 'lagrima'] },
      { emoji: '😭', keywords: ['chorando', 'muito', 'sobbing', 'loud', 'cry'] },
      { emoji: '😱', keywords: ['gritando', 'de', 'medo', 'screaming'] },
      { emoji: '😖', keywords: ['confundido', 'confounded'] },
      { emoji: '😞', keywords: ['desapontado', 'disappointed'] },
      { emoji: '😓', keywords: ['suor', 'frio', 'downcast', 'sweat'] },
      { emoji: '😩', keywords: ['exausto', 'weary', 'cansado'] },
      { emoji: '😫', keywords: ['cansado', 'tired'] },
      { emoji: '🥱', keywords: ['bocejando', 'yawning', 'sono'] },
      { emoji: '😤', keywords: ['bufando', 'triumph', 'raiva'] },
      { emoji: '😡', keywords: ['furioso', 'pouting', 'rage', 'raiva'] },
      { emoji: '😠', keywords: ['bravo', 'angry'] },
      { emoji: '🤬', keywords: ['xingando', 'cursing', 'palavrao'] },
      { emoji: '😈', keywords: ['diabinho', 'devil', 'imp'] },
      { emoji: '👿', keywords: ['diabo', 'imp', 'raiva'] },
      { emoji: '💀', keywords: ['caveira', 'skull', 'morto'] },
      { emoji: '☠️', keywords: ['cranio', 'ossos', 'skull', 'crossbones'] },
      { emoji: '💩', keywords: ['coco', 'poop'] },
      { emoji: '🤡', keywords: ['palhaco', 'clown'] },
      { emoji: '👻', keywords: ['fantasma', 'ghost'] },
      { emoji: '👽', keywords: ['alien', 'extraterrestre'] },
      { emoji: '🤖', keywords: ['robo', 'robot'] },
      { emoji: '🎃', keywords: ['abobora', 'halloween', 'pumpkin'] },
    ],
  },
  {
    id: 'people',
    emojis: [
      { emoji: '👋', keywords: ['tchau', 'wave', 'ola', 'aceno'] },
      { emoji: '🤚', keywords: ['mao', 'levantada', 'raised', 'hand'] },
      { emoji: '🖐️', keywords: ['mao', 'aberta', 'hand'] },
      { emoji: '✋', keywords: ['pare', 'stop', 'mao'] },
      { emoji: '🖖', keywords: ['saudacao', 'vulcana', 'vulcan'] },
      { emoji: '👌', keywords: ['ok', 'joia', 'perfect'] },
      { emoji: '🤌', keywords: ['dedos', 'juntos', 'pinched', 'italiano'] },
      { emoji: '🤏', keywords: ['pouquinho', 'pinching', 'pequeno'] },
      { emoji: '✌️', keywords: ['paz', 'victory', 'v'] },
      { emoji: '🤞', keywords: ['dedos', 'cruzados', 'crossed', 'fingers', 'sorte'] },
      { emoji: '🤟', keywords: ['amo', 'voce', 'love', 'you'] },
      { emoji: '🤘', keywords: ['rock', 'chifres', 'horns'] },
      { emoji: '🤙', keywords: ['me', 'liga', 'call', 'me'] },
      { emoji: '👈', keywords: ['aponta', 'esquerda', 'point', 'left'] },
      { emoji: '👉', keywords: ['aponta', 'direita', 'point', 'right'] },
      { emoji: '👆', keywords: ['aponta', 'cima', 'point', 'up'] },
      { emoji: '👇', keywords: ['aponta', 'baixo', 'point', 'down'] },
      { emoji: '☝️', keywords: ['dedo', 'indicador', 'index', 'up'] },
      { emoji: '👍', keywords: ['curtir', 'joia', 'thumbs', 'up', 'bom'] },
      { emoji: '👎', keywords: ['nao', 'curtir', 'thumbs', 'down', 'ruim'] },
      { emoji: '✊', keywords: ['punho', 'fist'] },
      { emoji: '👊', keywords: ['soco', 'punch', 'fist'] },
      { emoji: '👏', keywords: ['palmas', 'clap', 'aplauso'] },
      { emoji: '🙌', keywords: ['maos', 'para', 'cima', 'raising', 'hands', 'celebracao'] },
      { emoji: '👐', keywords: ['maos', 'abertas', 'open', 'hands'] },
      { emoji: '🤲', keywords: ['palmas', 'juntas', 'palms', 'up'] },
      { emoji: '🤝', keywords: ['aperto', 'de', 'mao', 'handshake', 'acordo'] },
      { emoji: '🙏', keywords: ['obrigado', 'please', 'pray', 'reza'] },
      { emoji: '✍️', keywords: ['escrevendo', 'writing', 'hand'] },
      { emoji: '💅', keywords: ['esmalte', 'nail', 'polish'] },
      { emoji: '💪', keywords: ['forca', 'muscle', 'biceps'] },
      { emoji: '🧠', keywords: ['cerebro', 'brain'] },
      { emoji: '👀', keywords: ['olhos', 'eyes', 'olhando'] },
      { emoji: '👁️', keywords: ['olho', 'eye'] },
      { emoji: '👶', keywords: ['bebe', 'baby'] },
      { emoji: '🧒', keywords: ['crianca', 'child'] },
      { emoji: '👦', keywords: ['menino', 'boy'] },
      { emoji: '👧', keywords: ['menina', 'girl'] },
      { emoji: '🧑', keywords: ['pessoa', 'person'] },
      { emoji: '👨', keywords: ['homem', 'man'] },
      { emoji: '👩', keywords: ['mulher', 'woman'] },
      { emoji: '🧓', keywords: ['idoso', 'older', 'person'] },
      { emoji: '🧑‍💻', keywords: ['pessoa', 'no', 'computador', 'technologist', 'dev'] },
      { emoji: '👨‍💻', keywords: ['homem', 'no', 'computador', 'developer', 'dev'] },
      { emoji: '👩‍💻', keywords: ['mulher', 'no', 'computador', 'developer', 'dev'] },
      { emoji: '🧑‍🏫', keywords: ['professor', 'teacher'] },
      { emoji: '🧑‍🎓', keywords: ['estudante', 'student', 'formatura'] },
      { emoji: '🧑‍🔬', keywords: ['cientista', 'scientist'] },
      { emoji: '🧑‍🚀', keywords: ['astronauta', 'astronaut'] },
      { emoji: '🕵️', keywords: ['detetive', 'detective', 'investigador'] },
      { emoji: '🦸', keywords: ['heroi', 'superhero'] },
      { emoji: '🧙', keywords: ['mago', 'wizard', 'mage'] },
      { emoji: '🧑‍🍳', keywords: ['chef', 'cozinheiro', 'cook'] },
      { emoji: '👮', keywords: ['policial', 'police'] },
      { emoji: '💃', keywords: ['dancarina', 'dancing'] },
      { emoji: '🕺', keywords: ['dancarino', 'dancing'] },
      { emoji: '🚶', keywords: ['andando', 'walking'] },
      { emoji: '🏃', keywords: ['correndo', 'running'] },
      { emoji: '🧘', keywords: ['meditando', 'yoga', 'lotus'] },
      { emoji: '🤷', keywords: ['dando', 'de', 'ombros', 'shrug', 'sei', 'la'] },
      { emoji: '🤦', keywords: ['mao', 'na', 'testa', 'facepalm'] },
      { emoji: '🙋', keywords: ['mao', 'levantada', 'raising', 'hand', 'pergunta'] },
      { emoji: '🙆', keywords: ['gesto', 'ok', 'ok', 'gesture'] },
      { emoji: '🙅', keywords: ['gesto', 'nao', 'no', 'gesture'] },
      { emoji: '💁', keywords: ['informacao', 'tipping', 'hand'] },
      { emoji: '👤', keywords: ['silhueta', 'bust', 'usuario', 'user'] },
      { emoji: '👥', keywords: ['duas', 'silhuetas', 'busts', 'equipe'] },
      { emoji: '👪', keywords: ['familia', 'family'] },
      { emoji: '❤️', keywords: ['coracao', 'vermelho', 'red', 'heart', 'amor', 'love'] },
      { emoji: '🧡', keywords: ['coracao', 'laranja', 'orange', 'heart'] },
      { emoji: '💛', keywords: ['coracao', 'amarelo', 'yellow', 'heart'] },
      { emoji: '💚', keywords: ['coracao', 'verde', 'green', 'heart'] },
      { emoji: '💙', keywords: ['coracao', 'azul', 'blue', 'heart'] },
      { emoji: '💜', keywords: ['coracao', 'roxo', 'purple', 'heart'] },
      { emoji: '🖤', keywords: ['coracao', 'preto', 'black', 'heart'] },
      { emoji: '🤍', keywords: ['coracao', 'branco', 'white', 'heart'] },
      { emoji: '💔', keywords: ['coracao', 'partido', 'broken', 'heart'] },
      { emoji: '💕', keywords: ['dois', 'coracoes', 'two', 'hearts'] },
      { emoji: '💖', keywords: ['coracao', 'brilhante', 'sparkling', 'heart'] },
      { emoji: '💯', keywords: ['cem', '100', 'nota', 'maxima', 'perfeito'] },
    ],
  },
  {
    id: 'nature',
    emojis: [
      { emoji: '🐶', keywords: ['cachorro', 'dog', 'cao'] },
      { emoji: '🐱', keywords: ['gato', 'cat'] },
      { emoji: '🐭', keywords: ['rato', 'mouse'] },
      { emoji: '🐹', keywords: ['hamster'] },
      { emoji: '🐰', keywords: ['coelho', 'rabbit'] },
      { emoji: '🦊', keywords: ['raposa', 'fox'] },
      { emoji: '🐻', keywords: ['urso', 'bear'] },
      { emoji: '🐼', keywords: ['panda'] },
      { emoji: '🐨', keywords: ['coala', 'koala'] },
      { emoji: '🐯', keywords: ['tigre', 'tiger'] },
      { emoji: '🦁', keywords: ['leao', 'lion'] },
      { emoji: '🐮', keywords: ['vaca', 'cow'] },
      { emoji: '🐷', keywords: ['porco', 'pig'] },
      { emoji: '🐸', keywords: ['sapo', 'frog'] },
      { emoji: '🐵', keywords: ['macaco', 'monkey'] },
      { emoji: '🙈', keywords: ['macaco', 'olhos', 'see', 'no', 'evil'] },
      { emoji: '🐔', keywords: ['galinha', 'chicken'] },
      { emoji: '🐧', keywords: ['pinguim', 'penguin'] },
      { emoji: '🐦', keywords: ['passaro', 'bird'] },
      { emoji: '🐤', keywords: ['pintinho', 'chick'] },
      { emoji: '🦆', keywords: ['pato', 'duck'] },
      { emoji: '🦅', keywords: ['aguia', 'eagle'] },
      { emoji: '🦉', keywords: ['coruja', 'owl'] },
      { emoji: '🦇', keywords: ['morcego', 'bat'] },
      { emoji: '🐺', keywords: ['lobo', 'wolf'] },
      { emoji: '🐗', keywords: ['javali', 'boar'] },
      { emoji: '🐴', keywords: ['cavalo', 'horse'] },
      { emoji: '🦄', keywords: ['unicornio', 'unicorn'] },
      { emoji: '🐝', keywords: ['abelha', 'bee'] },
      { emoji: '🐛', keywords: ['lagarta', 'caterpillar', 'bug'] },
      { emoji: '🦋', keywords: ['borboleta', 'butterfly'] },
      { emoji: '🐌', keywords: ['caracol', 'snail'] },
      { emoji: '🐞', keywords: ['joaninha', 'ladybug'] },
      { emoji: '🐜', keywords: ['formiga', 'ant'] },
      { emoji: '🕷️', keywords: ['aranha', 'spider'] },
      { emoji: '🐢', keywords: ['tartaruga', 'turtle'] },
      { emoji: '🐍', keywords: ['cobra', 'snake'] },
      { emoji: '🦎', keywords: ['lagarto', 'lizard'] },
      { emoji: '🐙', keywords: ['polvo', 'octopus'] },
      { emoji: '🦑', keywords: ['lula', 'squid'] },
      { emoji: '🦐', keywords: ['camarao', 'shrimp'] },
      { emoji: '🦀', keywords: ['caranguejo', 'crab'] },
      { emoji: '🐡', keywords: ['baiacu', 'blowfish'] },
      { emoji: '🐠', keywords: ['peixe', 'tropical', 'fish'] },
      { emoji: '🐟', keywords: ['peixe', 'fish'] },
      { emoji: '🐬', keywords: ['golfinho', 'dolphin'] },
      { emoji: '🐳', keywords: ['baleia', 'whale'] },
      { emoji: '🦈', keywords: ['tubarao', 'shark'] },
      { emoji: '🐊', keywords: ['crocodilo', 'crocodile'] },
      { emoji: '🐘', keywords: ['elefante', 'elephant'] },
      { emoji: '🦏', keywords: ['rinoceronte', 'rhino'] },
      { emoji: '🦒', keywords: ['girafa', 'giraffe'] },
      { emoji: '🐪', keywords: ['camelo', 'camel'] },
      { emoji: '🐑', keywords: ['ovelha', 'sheep'] },
      { emoji: '🐐', keywords: ['cabra', 'goat'] },
      { emoji: '🐓', keywords: ['galo', 'rooster'] },
      { emoji: '🦃', keywords: ['peru', 'turkey'] },
      { emoji: '🕊️', keywords: ['pomba', 'dove', 'paz'] },
      { emoji: '🌵', keywords: ['cacto', 'cactus'] },
      { emoji: '🎄', keywords: ['arvore', 'de', 'natal', 'christmas', 'tree'] },
      { emoji: '🌲', keywords: ['pinheiro', 'evergreen', 'tree', 'arvore'] },
      { emoji: '🌳', keywords: ['arvore', 'deciduous', 'tree'] },
      { emoji: '🌴', keywords: ['palmeira', 'palm', 'tree'] },
      { emoji: '🌱', keywords: ['muda', 'seedling', 'broto'] },
      { emoji: '🌿', keywords: ['erva', 'herb', 'folha'] },
      { emoji: '☘️', keywords: ['trevo', 'shamrock'] },
      { emoji: '🍀', keywords: ['trevo', 'de', 'quatro', 'folhas', 'four', 'leaf', 'clover', 'sorte'] },
      { emoji: '🍃', keywords: ['folhas', 'ao', 'vento', 'leaves', 'folha', 'leaf'] },
      { emoji: '🍂', keywords: ['folhas', 'caidas', 'fallen', 'leaves', 'outono'] },
      { emoji: '🍁', keywords: ['folha', 'de', 'bordo', 'maple', 'leaf'] },
      { emoji: '🌾', keywords: ['espiga', 'sheaf', 'rice'] },
      { emoji: '🌷', keywords: ['tulipa', 'tulip'] },
      { emoji: '🌹', keywords: ['rosa', 'rose'] },
      { emoji: '🌺', keywords: ['hibisco', 'hibiscus'] },
      { emoji: '🌸', keywords: ['flor', 'de', 'cerejeira', 'cherry', 'blossom'] },
      { emoji: '🌼', keywords: ['margarida', 'blossom', 'flor'] },
      { emoji: '🌻', keywords: ['girassol', 'sunflower'] },
      { emoji: '🌞', keywords: ['sol', 'com', 'rosto', 'sun', 'face'] },
      { emoji: '☀️', keywords: ['sol', 'sun', 'ensolarado'] },
      { emoji: '🌤️', keywords: ['sol', 'entre', 'nuvens', 'sun', 'behind', 'cloud'] },
      { emoji: '⛅', keywords: ['parcialmente', 'nublado', 'partly', 'cloudy'] },
      { emoji: '☁️', keywords: ['nuvem', 'cloud'] },
      { emoji: '🌧️', keywords: ['chuva', 'rain'] },
      { emoji: '⛈️', keywords: ['tempestade', 'storm', 'raio'] },
      { emoji: '🌩️', keywords: ['raio', 'lightning'] },
      { emoji: '❄️', keywords: ['floco', 'de', 'neve', 'snowflake'] },
      { emoji: '⛄', keywords: ['boneco', 'de', 'neve', 'snowman'] },
      { emoji: '🔥', keywords: ['fogo', 'fire', 'chamas', 'quente'] },
      { emoji: '💧', keywords: ['gota', 'droplet', 'agua'] },
      { emoji: '🌊', keywords: ['onda', 'wave', 'mar'] },
      { emoji: '🌈', keywords: ['arco', 'iris', 'rainbow'] },
      { emoji: '⭐', keywords: ['estrela', 'star'] },
      { emoji: '🌟', keywords: ['estrela', 'brilhante', 'glowing', 'star'] },
      { emoji: '✨', keywords: ['brilhos', 'sparkles'] },
      { emoji: '⚡', keywords: ['raio', 'zap', 'energia'] },
      { emoji: '🌙', keywords: ['lua', 'crescente', 'crescent', 'moon'] },
      { emoji: '🌍', keywords: ['planeta', 'terra', 'earth', 'globe', 'mundo'] },
      { emoji: '🪐', keywords: ['planeta', 'com', 'anel', 'saturno', 'planet'] },
    ],
  },
  {
    id: 'food',
    emojis: [
      { emoji: '🍏', keywords: ['maca', 'verde', 'green', 'apple'] },
      { emoji: '🍎', keywords: ['maca', 'apple'] },
      { emoji: '🍐', keywords: ['pera', 'pear'] },
      { emoji: '🍊', keywords: ['laranja', 'tangerine'] },
      { emoji: '🍋', keywords: ['limao', 'lemon'] },
      { emoji: '🍌', keywords: ['banana'] },
      { emoji: '🍉', keywords: ['melancia', 'watermelon'] },
      { emoji: '🍇', keywords: ['uva', 'grapes'] },
      { emoji: '🍓', keywords: ['morango', 'strawberry'] },
      { emoji: '🫐', keywords: ['mirtilo', 'blueberry'] },
      { emoji: '🍈', keywords: ['melao', 'melon'] },
      { emoji: '🍒', keywords: ['cereja', 'cherries'] },
      { emoji: '🍑', keywords: ['pessego', 'peach'] },
      { emoji: '🥭', keywords: ['manga', 'mango'] },
      { emoji: '🍍', keywords: ['abacaxi', 'pineapple'] },
      { emoji: '🥥', keywords: ['coco', 'coconut'] },
      { emoji: '🥝', keywords: ['kiwi'] },
      { emoji: '🍅', keywords: ['tomate', 'tomato'] },
      { emoji: '🥑', keywords: ['abacate', 'avocado'] },
      { emoji: '🥦', keywords: ['brocolis', 'broccoli'] },
      { emoji: '🥕', keywords: ['cenoura', 'carrot'] },
      { emoji: '🌽', keywords: ['milho', 'corn'] },
      { emoji: '🌶️', keywords: ['pimenta', 'hot', 'pepper'] },
      { emoji: '🥔', keywords: ['batata', 'potato'] },
      { emoji: '🍞', keywords: ['pao', 'bread'] },
      { emoji: '🥐', keywords: ['croissant'] },
      { emoji: '🥖', keywords: ['baguete', 'baguette'] },
      { emoji: '🧀', keywords: ['queijo', 'cheese'] },
      { emoji: '🥚', keywords: ['ovo', 'egg'] },
      { emoji: '🍳', keywords: ['ovo', 'frito', 'cooking', 'frigideira'] },
      { emoji: '🥞', keywords: ['panqueca', 'pancakes'] },
      { emoji: '🧇', keywords: ['waffle'] },
      { emoji: '🥓', keywords: ['bacon'] },
      { emoji: '🍔', keywords: ['hamburguer', 'burger'] },
      { emoji: '🍟', keywords: ['batata', 'frita', 'fries'] },
      { emoji: '🍕', keywords: ['pizza'] },
      { emoji: '🌭', keywords: ['cachorro', 'quente', 'hot', 'dog'] },
      { emoji: '🥪', keywords: ['sanduiche', 'sandwich'] },
      { emoji: '🌮', keywords: ['taco'] },
      { emoji: '🌯', keywords: ['burrito'] },
      { emoji: '🥗', keywords: ['salada', 'salad'] },
      { emoji: '🍝', keywords: ['macarrao', 'spaghetti', 'massa'] },
      { emoji: '🍜', keywords: ['lamen', 'ramen', 'sopa'] },
      { emoji: '🍲', keywords: ['ensopado', 'stew', 'panela'] },
      { emoji: '🍛', keywords: ['curry', 'arroz'] },
      { emoji: '🍣', keywords: ['sushi'] },
      { emoji: '🍤', keywords: ['camarao', 'frito', 'fried', 'shrimp'] },
      { emoji: '🍱', keywords: ['marmita', 'bento'] },
      { emoji: '🍚', keywords: ['arroz', 'rice'] },
      { emoji: '🥟', keywords: ['guioza', 'dumpling'] },
      { emoji: '🍦', keywords: ['sorvete', 'ice', 'cream'] },
      { emoji: '🍩', keywords: ['rosquinha', 'donut'] },
      { emoji: '🍪', keywords: ['biscoito', 'cookie'] },
      { emoji: '🎂', keywords: ['bolo', 'de', 'aniversario', 'birthday', 'cake'] },
      { emoji: '🍰', keywords: ['fatia', 'de', 'bolo', 'shortcake'] },
      { emoji: '🧁', keywords: ['cupcake'] },
      { emoji: '🥧', keywords: ['torta', 'pie'] },
      { emoji: '🍫', keywords: ['chocolate'] },
      { emoji: '🍬', keywords: ['bala', 'candy', 'doce'] },
      { emoji: '🍭', keywords: ['pirulito', 'lollipop'] },
      { emoji: '🍯', keywords: ['mel', 'honey'] },
      { emoji: '🥛', keywords: ['leite', 'milk', 'copo'] },
      { emoji: '☕', keywords: ['cafe', 'coffee'] },
      { emoji: '🍵', keywords: ['cha', 'tea'] },
      { emoji: '🧃', keywords: ['suco', 'juice'] },
      { emoji: '🥤', keywords: ['refrigerante', 'cup', 'straw'] },
      { emoji: '🍺', keywords: ['cerveja', 'beer'] },
      { emoji: '🍻', keywords: ['brinde', 'beers'] },
      { emoji: '🥂', keywords: ['tacas', 'clinking', 'glasses', 'brinde'] },
      { emoji: '🍷', keywords: ['vinho', 'wine'] },
      { emoji: '🥃', keywords: ['uisque', 'whisky'] },
      { emoji: '🍸', keywords: ['coquetel', 'cocktail'] },
      { emoji: '🧊', keywords: ['gelo', 'ice', 'cube'] },
    ],
  },
  {
    id: 'activity',
    emojis: [
      { emoji: '⚽', keywords: ['futebol', 'soccer', 'bola'] },
      { emoji: '🏀', keywords: ['basquete', 'basketball'] },
      { emoji: '🏈', keywords: ['futebol', 'americano', 'football'] },
      { emoji: '⚾', keywords: ['beisebol', 'baseball'] },
      { emoji: '🎾', keywords: ['tenis', 'tennis'] },
      { emoji: '🏐', keywords: ['volei', 'volleyball'] },
      { emoji: '🏉', keywords: ['rugby'] },
      { emoji: '🎱', keywords: ['sinuca', 'bilhar', '8', 'ball'] },
      { emoji: '🏓', keywords: ['tenis', 'de', 'mesa', 'ping', 'pong'] },
      { emoji: '🏸', keywords: ['badminton'] },
      { emoji: '🥅', keywords: ['gol', 'goal'] },
      { emoji: '🏒', keywords: ['hoquei', 'hockey'] },
      { emoji: '🥍', keywords: ['lacrosse'] },
      { emoji: '🏏', keywords: ['criquete', 'cricket'] },
      { emoji: '⛳', keywords: ['golfe', 'golf'] },
      { emoji: '🏹', keywords: ['arco', 'e', 'flecha', 'bow', 'arrow'] },
      { emoji: '🎣', keywords: ['pesca', 'fishing'] },
      { emoji: '🥊', keywords: ['boxe', 'boxing', 'luva'] },
      { emoji: '🥋', keywords: ['artes', 'marciais', 'martial', 'arts'] },
      { emoji: '🛹', keywords: ['skate', 'skateboard'] },
      { emoji: '🛼', keywords: ['patins', 'roller', 'skate'] },
      { emoji: '⛸️', keywords: ['patinacao', 'ice', 'skate'] },
      { emoji: '🎿', keywords: ['esqui', 'ski'] },
      { emoji: '🏂', keywords: ['snowboard'] },
      { emoji: '🏋️', keywords: ['musculacao', 'weight', 'lifting'] },
      { emoji: '🤸', keywords: ['ginastica', 'cartwheel'] },
      { emoji: '🤺', keywords: ['esgrima', 'fencing'] },
      { emoji: '🤼', keywords: ['luta', 'wrestling'] },
      { emoji: '🏊', keywords: ['natacao', 'swimming'] },
      { emoji: '🚴', keywords: ['ciclismo', 'cycling', 'bicicleta'] },
      { emoji: '🚵', keywords: ['mountain', 'bike'] },
      { emoji: '🏆', keywords: ['trofeu', 'trophy', 'premio'] },
      { emoji: '🥇', keywords: ['medalha', 'de', 'ouro', 'gold', 'medal', 'primeiro'] },
      { emoji: '🥈', keywords: ['medalha', 'de', 'prata', 'silver', 'medal'] },
      { emoji: '🥉', keywords: ['medalha', 'de', 'bronze', 'bronze', 'medal'] },
      { emoji: '🏅', keywords: ['medalha', 'medal'] },
      { emoji: '🎖️', keywords: ['medalha', 'militar', 'military', 'medal'] },
      { emoji: '🎯', keywords: ['alvo', 'dart', 'target', 'meta'] },
      { emoji: '🎲', keywords: ['dado', 'game', 'die', 'sorte'] },
      { emoji: '🎮', keywords: ['videogame', 'controle', 'game'] },
      { emoji: '🕹️', keywords: ['joystick', 'arcade'] },
      { emoji: '🎰', keywords: ['caca', 'niquel', 'slot'] },
      { emoji: '🧩', keywords: ['quebra', 'cabeca', 'puzzle'] },
      { emoji: '♟️', keywords: ['xadrez', 'chess', 'peao'] },
      { emoji: '🎭', keywords: ['teatro', 'performing', 'arts', 'mascaras'] },
      { emoji: '🎨', keywords: ['paleta', 'art', 'palette', 'arte'] },
      { emoji: '🎬', keywords: ['claquete', 'clapper', 'cinema', 'filme'] },
      { emoji: '🎤', keywords: ['microfone', 'microphone'] },
      { emoji: '🎧', keywords: ['fone', 'headphone'] },
      { emoji: '🎼', keywords: ['partitura', 'musical', 'score'] },
      { emoji: '🎵', keywords: ['nota', 'musical', 'music', 'note'] },
      { emoji: '🎶', keywords: ['notas', 'musicais', 'notes'] },
      { emoji: '🎹', keywords: ['piano', 'teclado'] },
      { emoji: '🥁', keywords: ['bateria', 'drum'] },
      { emoji: '🎷', keywords: ['saxofone', 'saxophone'] },
      { emoji: '🎺', keywords: ['trompete', 'trumpet'] },
      { emoji: '🎸', keywords: ['guitarra', 'violao', 'guitar'] },
      { emoji: '🎻', keywords: ['violino', 'violin'] },
    ],
  },
  {
    id: 'travel',
    emojis: [
      { emoji: '🚗', keywords: ['carro', 'car'] },
      { emoji: '🚕', keywords: ['taxi'] },
      { emoji: '🚙', keywords: ['suv', 'carro'] },
      { emoji: '🚌', keywords: ['onibus', 'bus'] },
      { emoji: '🏎️', keywords: ['carro', 'de', 'corrida', 'racing', 'car'] },
      { emoji: '🚓', keywords: ['viatura', 'police', 'car'] },
      { emoji: '🚑', keywords: ['ambulancia', 'ambulance'] },
      { emoji: '🚒', keywords: ['bombeiro', 'fire', 'engine'] },
      { emoji: '🚐', keywords: ['van', 'minibus'] },
      { emoji: '🚚', keywords: ['caminhao', 'truck'] },
      { emoji: '🚛', keywords: ['carreta', 'lorry'] },
      { emoji: '🚜', keywords: ['trator', 'tractor'] },
      { emoji: '🛵', keywords: ['scooter', 'moto'] },
      { emoji: '🏍️', keywords: ['moto', 'motorcycle'] },
      { emoji: '🚲', keywords: ['bicicleta', 'bicycle', 'bike'] },
      { emoji: '🛴', keywords: ['patinete', 'kick', 'scooter'] },
      { emoji: '🚨', keywords: ['sirene', 'alerta', 'police', 'light'] },
      { emoji: '🚝', keywords: ['monotrilho', 'monorail'] },
      { emoji: '🚄', keywords: ['trem', 'bala', 'high', 'speed', 'train'] },
      { emoji: '🚂', keywords: ['locomotiva', 'locomotive', 'trem'] },
      { emoji: '🚆', keywords: ['trem', 'train'] },
      { emoji: '🚇', keywords: ['metro'] },
      { emoji: '✈️', keywords: ['aviao', 'airplane', 'voo'] },
      { emoji: '🛫', keywords: ['decolagem', 'departure'] },
      { emoji: '🛬', keywords: ['pouso', 'arrival'] },
      { emoji: '🚀', keywords: ['foguete', 'rocket', 'lancamento'] },
      { emoji: '🛸', keywords: ['disco', 'voador', 'ufo'] },
      { emoji: '🚁', keywords: ['helicoptero', 'helicopter'] },
      { emoji: '⛵', keywords: ['veleiro', 'sailboat', 'barco'] },
      { emoji: '🚤', keywords: ['lancha', 'speedboat'] },
      { emoji: '🛳️', keywords: ['navio', 'de', 'passageiros', 'passenger', 'ship'] },
      { emoji: '⛴️', keywords: ['balsa', 'ferry'] },
      { emoji: '🚢', keywords: ['navio', 'ship'] },
      { emoji: '⚓', keywords: ['ancora', 'anchor'] },
      { emoji: '🗺️', keywords: ['mapa', 'mundi', 'world', 'map'] },
      { emoji: '🧭', keywords: ['bussola', 'compass'] },
      { emoji: '🏔️', keywords: ['montanha', 'nevada', 'snow', 'mountain'] },
      { emoji: '⛰️', keywords: ['montanha', 'mountain'] },
      { emoji: '🌋', keywords: ['vulcao', 'volcano'] },
      { emoji: '🏕️', keywords: ['acampamento', 'camping', 'barraca'] },
      { emoji: '🏖️', keywords: ['praia', 'beach'] },
      { emoji: '🏜️', keywords: ['deserto', 'desert'] },
      { emoji: '🏝️', keywords: ['ilha', 'deserta', 'island'] },
      { emoji: '🏟️', keywords: ['estadio', 'stadium'] },
      { emoji: '🏛️', keywords: ['construcao', 'classica', 'classical', 'building'] },
      { emoji: '🏗️', keywords: ['obra', 'building', 'construction', 'construcao'] },
      { emoji: '🏠', keywords: ['casa', 'house'] },
      { emoji: '🏡', keywords: ['casa', 'com', 'jardim', 'house', 'garden'] },
      { emoji: '🏢', keywords: ['predio', 'escritorio', 'office', 'building'] },
      { emoji: '🏣', keywords: ['correios', 'post', 'office'] },
      { emoji: '🏥', keywords: ['hospital'] },
      { emoji: '🏦', keywords: ['banco', 'bank'] },
      { emoji: '🏨', keywords: ['hotel'] },
      { emoji: '🏪', keywords: ['loja', 'de', 'conveniencia', 'convenience', 'store'] },
      { emoji: '🏫', keywords: ['escola', 'school'] },
      { emoji: '🏭', keywords: ['fabrica', 'factory'] },
      { emoji: '🏰', keywords: ['castelo', 'castle'] },
      { emoji: '🗼', keywords: ['torre', 'tower'] },
      { emoji: '🗽', keywords: ['estatua', 'da', 'liberdade', 'statue', 'liberty'] },
      { emoji: '⛩️', keywords: ['torii', 'santuario', 'shrine'] },
      { emoji: '🌁', keywords: ['neblina', 'foggy'] },
      { emoji: '🌃', keywords: ['noite', 'estrelada', 'night', 'stars'] },
      { emoji: '🏙️', keywords: ['cidade', 'cityscape'] },
      { emoji: '🌅', keywords: ['nascer', 'do', 'sol', 'sunrise'] },
      { emoji: '🌄', keywords: ['amanhecer', 'sunrise', 'mountains'] },
      { emoji: '🌆', keywords: ['entardecer', 'cityscape', 'dusk'] },
      { emoji: '🌇', keywords: ['por', 'do', 'sol', 'sunset'] },
      { emoji: '🌉', keywords: ['ponte', 'a', 'noite', 'bridge', 'night'] },
    ],
  },
  {
    id: 'objects',
    emojis: [
      { emoji: '⌚', keywords: ['relogio', 'watch'] },
      { emoji: '📱', keywords: ['celular', 'mobile', 'phone'] },
      { emoji: '💻', keywords: ['notebook', 'laptop', 'computador'] },
      { emoji: '🖥️', keywords: ['computador', 'desktop', 'monitor'] },
      { emoji: '🖨️', keywords: ['impressora', 'printer'] },
      { emoji: '⌨️', keywords: ['teclado', 'keyboard'] },
      { emoji: '🖱️', keywords: ['mouse'] },
      { emoji: '💾', keywords: ['disquete', 'floppy', 'salvar', 'save'] },
      { emoji: '💿', keywords: ['cd'] },
      { emoji: '📀', keywords: ['dvd'] },
      { emoji: '🧮', keywords: ['abaco', 'abacus'] },
      { emoji: '🎥', keywords: ['camera', 'de', 'cinema', 'movie', 'camera'] },
      { emoji: '📷', keywords: ['camera', 'fotografica', 'photo'] },
      { emoji: '📸', keywords: ['camera', 'com', 'flash'] },
      { emoji: '📹', keywords: ['filmadora', 'video', 'camera'] },
      { emoji: '📼', keywords: ['fita', 'cassete', 'videotape'] },
      { emoji: '🔍', keywords: ['lupa', 'buscar', 'search', 'magnifying'] },
      { emoji: '🔎', keywords: ['lupa', 'direita', 'magnifying', 'search'] },
      { emoji: '🔬', keywords: ['microscopio', 'microscope'] },
      { emoji: '🔭', keywords: ['telescopio', 'telescope'] },
      { emoji: '📡', keywords: ['antena', 'satellite', 'antenna'] },
      { emoji: '🕯️', keywords: ['vela', 'candle'] },
      { emoji: '💡', keywords: ['lampada', 'ideia', 'light', 'bulb'] },
      { emoji: '🔦', keywords: ['lanterna', 'flashlight'] },
      { emoji: '🏮', keywords: ['lanterna', 'vermelha', 'lantern'] },
      { emoji: '📔', keywords: ['caderno', 'decorado', 'notebook'] },
      { emoji: '📕', keywords: ['livro', 'fechado', 'closed', 'book'] },
      { emoji: '📖', keywords: ['livro', 'aberto', 'open', 'book', 'ler'] },
      { emoji: '📗', keywords: ['livro', 'verde', 'green', 'book'] },
      { emoji: '📘', keywords: ['livro', 'azul', 'blue', 'book'] },
      { emoji: '📙', keywords: ['livro', 'laranja', 'orange', 'book'] },
      { emoji: '📚', keywords: ['livros', 'books', 'biblioteca'] },
      { emoji: '📓', keywords: ['caderno', 'notebook'] },
      { emoji: '📒', keywords: ['caderno', 'de', 'contas', 'ledger'] },
      { emoji: '📃', keywords: ['pagina', 'page'] },
      { emoji: '📜', keywords: ['pergaminho', 'scroll'] },
      { emoji: '📄', keywords: ['documento', 'document', 'page'] },
      { emoji: '📰', keywords: ['jornal', 'noticia', 'newspaper'] },
      { emoji: '🗞️', keywords: ['jornal', 'enrolado', 'rolled', 'newspaper'] },
      { emoji: '📑', keywords: ['marcadores', 'bookmark', 'tabs'] },
      { emoji: '🔖', keywords: ['marcador', 'bookmark'] },
      { emoji: '🏷️', keywords: ['etiqueta', 'label', 'tag'] },
      { emoji: '💰', keywords: ['saco', 'de', 'dinheiro', 'money', 'bag'] },
      { emoji: '💵', keywords: ['dolar', 'dollar'] },
      { emoji: '💶', keywords: ['euro'] },
      { emoji: '💷', keywords: ['libra', 'pound'] },
      { emoji: '💸', keywords: ['dinheiro', 'voando', 'money', 'wings'] },
      { emoji: '💳', keywords: ['cartao', 'de', 'credito', 'credit', 'card'] },
      { emoji: '🧾', keywords: ['recibo', 'nota', 'receipt'] },
      { emoji: '💎', keywords: ['diamante', 'gem', 'joia'] },
      { emoji: '⚖️', keywords: ['balanca', 'justica', 'scales'] },
      { emoji: '🔧', keywords: ['chave', 'inglesa', 'wrench', 'ferramenta'] },
      { emoji: '🔨', keywords: ['martelo', 'hammer'] },
      { emoji: '🛠️', keywords: ['ferramentas', 'tools'] },
      { emoji: '⛏️', keywords: ['picareta', 'pick'] },
      { emoji: '🔩', keywords: ['parafuso', 'nut', 'bolt'] },
      { emoji: '⚙️', keywords: ['engrenagem', 'configuracao', 'gear'] },
      { emoji: '🧰', keywords: ['caixa', 'de', 'ferramentas', 'toolbox'] },
      { emoji: '🧲', keywords: ['ima', 'magnet'] },
      { emoji: '💣', keywords: ['bomba', 'bomb'] },
      { emoji: '🧨', keywords: ['dinamite', 'firecracker'] },
      { emoji: '🪓', keywords: ['machado', 'axe'] },
      { emoji: '🔪', keywords: ['faca', 'knife'] },
      { emoji: '🗡️', keywords: ['espada', 'dagger'] },
      { emoji: '⚔️', keywords: ['espadas', 'crossed', 'swords'] },
      { emoji: '🛡️', keywords: ['escudo', 'shield'] },
      { emoji: '⚰️', keywords: ['caixao', 'coffin'] },
      { emoji: '🔮', keywords: ['bola', 'de', 'cristal', 'crystal', 'ball'] },
      { emoji: '📿', keywords: ['rosario', 'prayer', 'beads'] },
      { emoji: '⚗️', keywords: ['alambique', 'quimica', 'alembic'] },
      { emoji: '🧪', keywords: ['tubo', 'de', 'ensaio', 'test', 'tube'] },
      { emoji: '🧫', keywords: ['placa', 'de', 'petri', 'petri', 'dish'] },
      { emoji: '🧬', keywords: ['dna'] },
      { emoji: '🦠', keywords: ['microorganismo', 'virus', 'microbe'] },
      { emoji: '💊', keywords: ['remedio', 'pill'] },
      { emoji: '💉', keywords: ['seringa', 'vacina', 'syringe'] },
      { emoji: '🩹', keywords: ['curativo', 'bandage'] },
      { emoji: '🩺', keywords: ['estetoscopio', 'stethoscope'] },
      { emoji: '🚪', keywords: ['porta', 'door'] },
      { emoji: '🛏️', keywords: ['cama', 'bed'] },
      { emoji: '🛋️', keywords: ['sofa', 'couch'] },
      { emoji: '🪑', keywords: ['cadeira', 'chair'] },
      { emoji: '🚿', keywords: ['chuveiro', 'shower'] },
      { emoji: '🛁', keywords: ['banheira', 'bathtub'] },
      { emoji: '🧹', keywords: ['vassoura', 'limpar', 'broom'] },
      { emoji: '🧺', keywords: ['cesto', 'basket'] },
      { emoji: '🧻', keywords: ['papel', 'higienico', 'toilet', 'paper'] },
      { emoji: '🧼', keywords: ['sabonete', 'soap'] },
      { emoji: '🧴', keywords: ['frasco', 'lotion'] },
      { emoji: '🔑', keywords: ['chave', 'key'] },
      { emoji: '🗝️', keywords: ['chave', 'antiga', 'old', 'key'] },
      { emoji: '🔒', keywords: ['cadeado', 'fechado', 'locked'] },
      { emoji: '🔓', keywords: ['cadeado', 'aberto', 'unlocked'] },
      { emoji: '🔐', keywords: ['cadeado', 'com', 'chave', 'locked', 'key'] },
      { emoji: '📦', keywords: ['caixa', 'pacote', 'package'] },
      { emoji: '📫', keywords: ['caixa', 'de', 'correio', 'mailbox'] },
      { emoji: '📮', keywords: ['caixa', 'postal', 'postbox'] },
      { emoji: '✉️', keywords: ['envelope', 'carta', 'email'] },
      { emoji: '📧', keywords: ['email'] },
      { emoji: '📨', keywords: ['email', 'recebido', 'incoming', 'envelope'] },
      { emoji: '📩', keywords: ['email', 'enviado', 'envelope', 'arrow'] },
      { emoji: '📤', keywords: ['caixa', 'de', 'saida', 'outbox'] },
      { emoji: '📥', keywords: ['caixa', 'de', 'entrada', 'inbox'] },
      { emoji: '🗳️', keywords: ['urna', 'voto', 'ballot', 'box'] },
      { emoji: '✏️', keywords: ['lapis', 'pencil'] },
      { emoji: '✒️', keywords: ['caneta', 'tinteiro', 'pen', 'nib'] },
      { emoji: '🖋️', keywords: ['caneta', 'fountain', 'pen'] },
      { emoji: '🖊️', keywords: ['caneta', 'pen'] },
      { emoji: '🖌️', keywords: ['pincel', 'paintbrush'] },
      { emoji: '🖍️', keywords: ['giz', 'de', 'cera', 'crayon'] },
      { emoji: '📝', keywords: ['anotacao', 'nota', 'escrever', 'memo'] },
      { emoji: '📁', keywords: ['pasta', 'folder'] },
      { emoji: '📂', keywords: ['pasta', 'aberta', 'open', 'folder'] },
      { emoji: '🗂️', keywords: ['divisorias', 'card', 'index', 'dividers'] },
      { emoji: '📅', keywords: ['calendario', 'data', 'calendar'] },
      { emoji: '📆', keywords: ['calendario', 'calendar'] },
      { emoji: '🗓️', keywords: ['calendario', 'spiral', 'calendar'] },
      { emoji: '📇', keywords: ['fichario', 'card', 'index'] },
      { emoji: '📈', keywords: ['grafico', 'crescente', 'alta', 'chart', 'increasing'] },
      { emoji: '📉', keywords: ['grafico', 'caindo', 'queda', 'chart', 'decreasing'] },
      { emoji: '📊', keywords: ['grafico', 'de', 'barras', 'bar', 'chart'] },
      { emoji: '📋', keywords: ['prancheta', 'clipboard'] },
      { emoji: '📌', keywords: ['alfinete', 'pushpin'] },
      { emoji: '📍', keywords: ['marcador', 'local', 'round', 'pushpin'] },
      { emoji: '📎', keywords: ['clipe', 'paperclip'] },
      { emoji: '🖇️', keywords: ['clipes', 'linked', 'paperclips'] },
      { emoji: '📏', keywords: ['regua', 'ruler'] },
      { emoji: '📐', keywords: ['esquadro', 'triangular', 'ruler'] },
      { emoji: '✂️', keywords: ['tesoura', 'scissors'] },
      { emoji: '🗃️', keywords: ['arquivo', 'card', 'file', 'box'] },
      { emoji: '🗄️', keywords: ['arquivo', 'file', 'cabinet'] },
      { emoji: '🗑️', keywords: ['lixeira', 'trash', 'wastebasket'] },
    ],
  },
  {
    id: 'symbols',
    emojis: [
      { emoji: '✅', keywords: ['check', 'verde', 'feito', 'ok', 'check', 'mark'] },
      { emoji: '☑️', keywords: ['caixa', 'marcada', 'ballot', 'check'] },
      { emoji: '✔️', keywords: ['check', 'check', 'mark'] },
      { emoji: '❌', keywords: ['x', 'errado', 'cross', 'mark'] },
      { emoji: '❎', keywords: ['x', 'cruz', 'cross', 'mark'] },
      { emoji: '➕', keywords: ['mais', 'plus'] },
      { emoji: '➖', keywords: ['menos', 'minus'] },
      { emoji: '➗', keywords: ['divisao', 'divide'] },
      { emoji: '✖️', keywords: ['multiplicacao', 'multiply'] },
      { emoji: '❓', keywords: ['interrogacao', 'duvida', 'question'] },
      { emoji: '❗', keywords: ['exclamacao', 'exclamation'] },
      { emoji: '‼️', keywords: ['dupla', 'exclamacao', 'double', 'exclamation'] },
      { emoji: '⁉️', keywords: ['exclamacao', 'interrogacao'] },
      { emoji: '⚠️', keywords: ['atencao', 'alerta', 'warning'] },
      { emoji: '🚫', keywords: ['proibido', 'prohibited'] },
      { emoji: '⛔', keywords: ['entrada', 'proibida', 'no', 'entry'] },
      { emoji: '📵', keywords: ['sem', 'celular', 'no', 'mobile'] },
      { emoji: '🔕', keywords: ['sem', 'som', 'mudo', 'bell', 'slash'] },
      { emoji: '🔔', keywords: ['sino', 'notificacao', 'bell'] },
      { emoji: '🔊', keywords: ['som', 'alto', 'speaker', 'volume'] },
      { emoji: '🔇', keywords: ['mudo', 'muted'] },
      { emoji: '📢', keywords: ['megafone', 'anuncio', 'loudspeaker'] },
      { emoji: '📣', keywords: ['megafone', 'megaphone'] },
      { emoji: '💬', keywords: ['balao', 'de', 'fala', 'comentario', 'speech', 'balloon'] },
      { emoji: '💭', keywords: ['balao', 'de', 'pensamento', 'thought', 'balloon'] },
      { emoji: '♻️', keywords: ['reciclagem', 'recycle'] },
      { emoji: '🔄', keywords: ['recarregar', 'atualizar', 'sync'] },
      { emoji: '🔀', keywords: ['aleatorio', 'shuffle'] },
      { emoji: '🔁', keywords: ['repetir', 'loop', 'repeat'] },
      { emoji: '▶️', keywords: ['play'] },
      { emoji: '⏸️', keywords: ['pausa', 'pause'] },
      { emoji: '⏹️', keywords: ['parar', 'stop'] },
      { emoji: '⏺️', keywords: ['gravar', 'record'] },
      { emoji: '⏭️', keywords: ['proximo', 'next', 'track'] },
      { emoji: '⏮️', keywords: ['anterior', 'previous', 'track'] },
      { emoji: '⏩', keywords: ['avancar', 'fast', 'forward'] },
      { emoji: '⏪', keywords: ['retroceder', 'rewind'] },
      { emoji: '⬆️', keywords: ['seta', 'cima', 'up', 'arrow'] },
      { emoji: '⬇️', keywords: ['seta', 'baixo', 'down', 'arrow'] },
      { emoji: '⬅️', keywords: ['seta', 'esquerda', 'left', 'arrow'] },
      { emoji: '➡️', keywords: ['seta', 'direita', 'right', 'arrow'] },
      { emoji: '↗️', keywords: ['seta', 'diagonal', 'up', 'right'] },
      { emoji: '↘️', keywords: ['seta', 'diagonal', 'down', 'right'] },
      { emoji: '↩️', keywords: ['voltar', 'return'] },
      { emoji: '↪️', keywords: ['avancar', 'forward'] },
      { emoji: '🔗', keywords: ['link', 'corrente'] },
      { emoji: '📶', keywords: ['sinal', 'antenna', 'bars'] },
      { emoji: '🔋', keywords: ['bateria', 'battery'] },
      { emoji: '🔌', keywords: ['tomada', 'plug', 'electric'] },
      { emoji: '⏰', keywords: ['despertador', 'alarm', 'clock'] },
      { emoji: '⏱️', keywords: ['cronometro', 'stopwatch'] },
      { emoji: '⏳', keywords: ['ampulheta', 'tempo', 'hourglass'] },
      { emoji: '🕐', keywords: ['relogio', 'hora', 'one', 'oclock'] },
      { emoji: '🆕', keywords: ['novo', 'new'] },
      { emoji: '🆗', keywords: ['ok'] },
      { emoji: '🆙', keywords: ['up'] },
      { emoji: '🆒', keywords: ['cool'] },
      { emoji: '🆓', keywords: ['gratis', 'free'] },
      { emoji: '🔝', keywords: ['topo', 'top'] },
      { emoji: '🔜', keywords: ['em', 'breve', 'soon'] },
      { emoji: '🔙', keywords: ['voltar', 'back'] },
      { emoji: '🔛', keywords: ['ligado', 'on'] },
      { emoji: '🔢', keywords: ['numeros', 'numbers'] },
      { emoji: '🔤', keywords: ['letras', 'abc'] },
      { emoji: '🔠', keywords: ['maiusculas', 'uppercase'] },
      { emoji: '🔡', keywords: ['minusculas', 'lowercase'] },
      { emoji: '💠', keywords: ['losango', 'diamond'] },
      { emoji: '🔘', keywords: ['botao', 'radio', 'button'] },
      { emoji: '🔴', keywords: ['circulo', 'vermelho', 'red', 'circle'] },
      { emoji: '🟠', keywords: ['circulo', 'laranja', 'orange', 'circle'] },
      { emoji: '🟡', keywords: ['circulo', 'amarelo', 'yellow', 'circle'] },
      { emoji: '🟢', keywords: ['circulo', 'verde', 'green', 'circle'] },
      { emoji: '🔵', keywords: ['circulo', 'azul', 'blue', 'circle'] },
      { emoji: '🟣', keywords: ['circulo', 'roxo', 'purple', 'circle'] },
      { emoji: '⚫', keywords: ['circulo', 'preto', 'black', 'circle'] },
      { emoji: '⚪', keywords: ['circulo', 'branco', 'white', 'circle'] },
      { emoji: '🟥', keywords: ['quadrado', 'vermelho', 'red', 'square'] },
      { emoji: '🟧', keywords: ['quadrado', 'laranja', 'orange', 'square'] },
      { emoji: '🟨', keywords: ['quadrado', 'amarelo', 'yellow', 'square'] },
      { emoji: '🟩', keywords: ['quadrado', 'verde', 'green', 'square'] },
      { emoji: '🟦', keywords: ['quadrado', 'azul', 'blue', 'square'] },
      { emoji: '🟪', keywords: ['quadrado', 'roxo', 'purple', 'square'] },
      { emoji: '⬛', keywords: ['quadrado', 'preto', 'black', 'square'] },
      { emoji: '⬜', keywords: ['quadrado', 'branco', 'white', 'square'] },
    ],
  },
]

export const allEmojis: ReadonlyArray<EmojiEntry> = emojiGroups.flatMap(
  (group) => group.emojis,
)

export function normalizeEmojiQuery(value: string): string {
  return value
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .trim()
}

export function searchEmojis(
  query: string,
  limit = 240,
): ReadonlyArray<EmojiEntry> {
  const terms = normalizeEmojiQuery(query).split(/\s+/).filter(Boolean)

  if (terms.length === 0) {
    return []
  }

  const matches: EmojiEntry[] = []

  for (const entry of allEmojis) {
    const hit = terms.every(
      (term) =>
        entry.emoji === term ||
        entry.keywords.some((keyword) => keyword.includes(term)),
    )

    if (hit) {
      matches.push(entry)

      if (matches.length === limit) {
        break
      }
    }
  }

  return matches
}

export function randomEmoji(random: () => number = Math.random): string {
  const index = Math.min(
    allEmojis.length - 1,
    Math.max(0, Math.floor(random() * allEmojis.length)),
  )

  return allEmojis[index]?.emoji ?? '📄'
}
